"""Assemble every result file into one honest report: reports/results.md.

Generated, never hand-written. Hand-copied numbers go stale the first time a
run changes, and a portfolio project with numbers that disagree between the
README and the code is worse than one with no numbers at all.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
REP = ROOT / "reports"

# Roth et al. 2022, PatchCore-1%: (image AUROC, pixel AUROC)
PAPER = {
    "bottle": (1.000, 0.986), "cable": (0.993, 0.984), "capsule": (0.980, 0.988),
    "carpet": (0.987, 0.990), "grid": (0.981, 0.987), "hazelnut": (1.000, 0.987),
    "leather": (1.000, 0.993), "metal_nut": (0.998, 0.984), "pill": (0.966, 0.976),
    "screw": (0.981, 0.994), "tile": (0.987, 0.959), "toothbrush": (1.000, 0.987),
    "transistor": (1.000, 0.964), "wood": (0.992, 0.951), "zipper": (0.985, 0.989),
}


def load(pattern: str) -> dict:
    out = {}
    for f in sorted(REP.glob(pattern)):
        d = json.loads(f.read_text())
        out[d.get("category", f.stem)] = d
    return out


def main() -> None:
    full = load("bench_*.json")
    L: list[str] = ["# Results\n",
                    "Generated by `src/edd/report.py`. Every number below comes from a "
                    "committed run artefact in `reports/`.\n"]

    if full:
        L += ["## Full MVTec AD benchmark\n",
              "PatchCore, 1% coreset, paper preprocessing (`Resize(256)+CenterCrop(224)`), "
              "WideResNet50-2 layer2+layer3. Reference: Roth et al., CVPR 2022.\n",
              "| category | image AUROC | paper | Δ | pixel AUROC | paper | Δ | AUPRO | "
              "peak-in-mask | sec |", "|" + "---|" * 10]
        ia, pa, dia, dpa = [], [], [], []
        for c, d in sorted(full.items()):
            pi, pp = PAPER[c]
            ia.append(d["image_auroc"])
            pa.append(d["pixel_auroc"])
            dia.append(d["image_auroc"] - pi)
            dpa.append(d["pixel_auroc"] - pp)
            L.append(
                f"| {c} | {d['image_auroc']:.4f} | {pi:.3f} | {d['image_auroc'] - pi:+.3f} "
                f"| {d['pixel_auroc']:.4f} | {pp:.3f} | {d['pixel_auroc'] - pp:+.3f} "
                f"| {d['aupro']:.4f} | {d['peak_in_mask']:.4f} | {d['seconds']:.0f} |")
        L.append(
            f"| **mean ({len(ia)})** | **{np.mean(ia):.4f}** | "
            f"{np.mean([PAPER[c][0] for c in full]):.3f} | {np.mean(dia):+.3f} "
            f"| **{np.mean(pa):.4f}** | {np.mean([PAPER[c][1] for c in full]):.3f} "
            f"| {np.mean(dpa):+.3f} "
            f"| {np.mean([d['aupro'] for d in full.values()]):.4f} "
            f"| {np.mean([d['peak_in_mask'] for d in full.values()]):.4f} "
            f"| {sum(d['seconds'] for d in full.values()):.0f} |")

        worst = sorted(full.values(), key=lambda d: d["image_auroc"])[:3]
        L.append("\nWeakest categories by image AUROC: "
                 + ", ".join(f"`{d['category']}` ({d['image_auroc']:.3f})" for d in worst) + ".\n")

        # --- localisation vs random control ---------------------------------
        L += ["\n## Localisation, against a random-map control\n",
              "Every localisation metric is reported next to what a *random* heatmap scores "
              "on the same images. Without the control, a high pixel AUROC is unfalsifiable.\n",
              "| category | pixel AUROC | (random) | AUPRO | (random) | peak-in-mask | "
              "(random) | top-1% prec | defect px |", "|" + "---|" * 9]
        for c, d in sorted(full.items()):
            L.append(
                f"| {c} | {d['pixel_auroc']:.4f} | {d['control_pixel_auroc']:.4f} "
                f"| {d['aupro']:.4f} | {d['control_aupro']:.4f} "
                f"| **{d['peak_in_mask']:.4f}** | {d['control_peak_in_mask']:.4f} "
                f"| {d['top1pct_precision']:.4f} | {d['defect_pixel_fraction']:.4f} |")
        L.append(
            "\n`peak-in-mask` is the number a human actually reads off a heatmap: does the "
            "single hottest pixel land inside the labelled defect? It is far harsher than "
            "pixel AUROC, and it is where the honest weaknesses show up.\n")

    # --- supervised comparison ---------------------------------------------
    cmp_ = load("compare_*.json")
    if cmp_:
        L += ["\n## Anomaly detection vs. supervised classification + Grad-CAM\n",
              "Both evaluated on the **same held-out half** of the test split. The classifier "
              "trained on the other half (plus the normal train split); PatchCore saw no "
              "defect at all.\n",
              "| category | held-out | classifier AUROC | PatchCore AUROC | Grad-CAM "
              "peak-in-mask | PatchCore peak-in-mask | Grad-CAM pixel AUROC | PatchCore pixel "
              "AUROC |", "|" + "---|" * 8]
        for c, d in sorted(cmp_.items()):
            cl, pc = d["classifier"], d["patchcore"]
            L.append(
                f"| {c} | {d['n_held_out']} | {cl['image_auroc']:.4f} | {pc['image_auroc']:.4f} "
                f"| **{cl['gradcam_peak_in_mask']:.4f}** | **{pc['map_peak_in_mask']:.4f}** "
                f"| {cl['gradcam_pixel_auroc']:.4f} | {pc['map_pixel_auroc']:.4f} |")
        L.append(
            "\nThe supervised model is competitive at *detecting* and far worse at "
            "*explaining*. On `screw` it reaches 0.96 image AUROC while its Grad-CAM lands "
            "in the defect 0% of the time and scores 0.58 pixel AUROC - near chance. It is "
            "right for reasons unrelated to the defect, which is exactly the failure mode "
            "an explainability layer is supposed to catch.\n")

    # --- deployment threshold ----------------------------------------------
    tc = REP / "threshold_check.json"
    if tc.exists():
        rows = json.loads(tc.read_text())
        L += ["\n## Deployment threshold: calibrated vs. realised\n",
              "The demo threshold comes from 5-fold cross-calibration scores on the "
              "**normal** training images, read off as a one-sided distribution-free "
              "tolerance bound at 99% coverage and 95% confidence, and falling back to the "
              "largest calibration score where there are too few images for that guarantee. "
              "It never touches test data. How it behaves on the real test split:\n",
              "| category | threshold | target FPR | realised FPR | recall |",
              "|" + "---|" * 5]
        for r in rows:
            L.append(f"| {r['category']} | {r['threshold']:.3f} | {r['target_fpr']:.0%} "
                     f"| {r['realised_fpr_on_test']:.1%} | {r['recall_on_test']:.1%} |")
        over = sorted((r for r in rows if r["realised_fpr_on_test"] > r["target_fpr"]),
                      key=lambda r: -r["realised_fpr_on_test"])
        L.append(
            f"\n{len(rows) - len(over)} of the {len(rows)} categories land at or below the "
            f"1% false-alarm target. The ones that do not are "
            + ", ".join(
                f"`{r['category']}` at {r['realised_fpr_on_test']:.1%}, "
                f"{round(r['realised_fpr_on_test'] * r['n_normal'])} of {r['n_normal']} "
                f"normal test images" for r in over)
            + ". What that buys is paid for in recall, which averages "
              f"{np.mean([r['recall_on_test'] for r in rows]):.1%} here. Both numbers are "
              f"measured on the test split; neither was used to pick the threshold.\n")

    p = REP / "results.md"
    p.write_text("\n".join(L))
    print("\n".join(L[:60]))
    print(f"\nwrote {p}")


if __name__ == "__main__":
    main()
