"""Run the headline config with several seeds and report the spread.

The backbone is frozen and the test images are fixed, so the only randomness
is in two places, and both take the seed:

  - the coreset: the random projection it searches in and its starting point
  - the threshold: which training images land in which calibration fold

Features are extracted once per category and reused for every seed, which is
what keeps five seeds affordable on a laptop.

For each seed this writes image AUROC, pixel AUROC and AUPRO (computed as in
explain.py, over the whole test split) and the false-alarm rate on the test
normals at the shipped threshold rule (5-fold calibration, tolerance bound,
1% target), with a Wilson 95% interval.

Run:  python src/edd/seeds.py [categories...] [--seeds 5]
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

import numpy as np
import torch
from baseline import evaluate
from dataset import MVTecCategory
from explain import localisation_metrics
from export import calibration_scores, choose_threshold
from patchcore import PatchFeatures, coreset, device, device_name, extract, score, to_maps

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "reports" / "seeds"
CATEGORIES = ["bottle", "cable", "capsule", "carpet", "grid", "hazelnut", "leather",
              "metal_nut", "pill", "screw", "tile", "toothbrush", "transistor", "wood", "zipper"]


def wilson(k: int, n: int, z: float = 1.959964) -> tuple[float, float]:
    """Wilson score interval for k successes out of n. Exact 0 and 1 at the ends."""
    if n == 0:
        return float("nan"), float("nan")
    p = k / n
    centre = (p + z * z / (2 * n)) / (1 + z * z / n)
    half = z / (1 + z * z / n) * np.sqrt(p * (1 - p) / n + z * z / (4 * n * n))
    return (0.0 if k == 0 else float(centre - half)), (1.0 if k == n else float(centre + half))


def run(category: str, seeds: list[int], frac: float = 0.01, size: int = 224) -> dict:
    dev = device()
    model = PatchFeatures().to(dev)
    t0 = time.time()
    tr, _, _, _, grid = extract(model, MVTecCategory(category, "train", size, True), dev)
    te, labels, masks, _, _ = extract(model, MVTecCategory(category, "test", size, True), dev)
    masks = masks.numpy()[:, 0]
    flat = tr.reshape(-1, tr.shape[-1])
    normal = labels == 0
    rows = []
    for seed in seeds:
        torch.manual_seed(seed)
        bank = flat[coreset(flat, frac, dev, seed)]
        ps = score(bank, te, dev)
        img = ps.max(dim=1).values.numpy()
        maps = to_maps(ps, grid, size).numpy()[:, 0]
        loc = localisation_metrics(maps, masks, np.random.default_rng(seed))["model"]

        cal = calibration_scores(tr, frac, dev, 5, seed)
        thr, meta = choose_threshold(cal, 0.01, "tolerance")
        fa = int((img[normal] >= thr).sum())
        lo, hi = wilson(fa, int(normal.sum()))
        rows.append({
            "seed": seed,
            "image_auroc": evaluate(labels, img)["image_auroc"],
            "pixel_auroc": loc["pixel_auroc"], "aupro": loc["aupro"],
            "threshold": thr, "guarantee_met": meta["guarantee_met"],
            "false_alarms": fa, "n_normal": int(normal.sum()),
            "far": fa / int(normal.sum()), "far_wilson95": [lo, hi],
            "recall": float((img[~normal] >= thr).mean()),
        })
        r = rows[-1]
        print(f"{category:11} seed {seed} | img {r['image_auroc']:.4f} | px {r['pixel_auroc']:.4f}"
              f" | aupro {r['aupro']:.4f} | FAR {fa}/{r['n_normal']} [{lo:.3f}, {hi:.3f}]",
              flush=True)

    out = {"category": category, "device": device_name(dev), "coreset_frac": frac, "input_size": size, "center_crop": True,
           "n_train": int(tr.shape[0]), "n_test": len(labels), "seeds": rows,
           "seconds": round(time.time() - t0, 1)}
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / f"{category}.json").write_text(json.dumps(out, indent=1))
    return out


def table() -> str:
    """reports/seeds.md from whatever reports/seeds/*.json exist."""
    runs = [json.loads((OUT / f"{c}.json").read_text()) for c in CATEGORIES
            if (OUT / f"{c}.json").exists()]
    n_seeds = {len(r["seeds"]) for r in runs}
    o = ["# Seed spread\n",
         f"Generated by `src/edd/seeds.py`. {len(runs)} categories, "
         f"{'/'.join(map(str, sorted(n_seeds)))} seeds each. Mean and sample standard "
         "deviation over seeds. Pixel AUROC and AUPRO are over the whole test split, "
         "AUPRO up to FPR 0.3.\n",
         "| category | image AUROC | pixel AUROC | AUPRO |", "|---|---|---|---|"]

    def ms(r, k):
        v = np.array([s[k] for s in r["seeds"]])
        return v.mean(), v.std(ddof=1) if len(v) > 1 else 0.0

    cols = ("image_auroc", "pixel_auroc", "aupro")
    for r in runs:
        o.append(f"| {r['category']} | " + " | ".join(
            "{:.4f} ± {:.4f}".format(*ms(r, k)) for k in cols) + " |")
    # the mean over categories, taken per seed, then spread over seeds
    per_seed = {k: np.mean([[s[k] for s in r["seeds"]] for r in runs], axis=0) for k in cols}
    o.append("| mean | " + " | ".join(
        f"{per_seed[k].mean():.4f} ± {per_seed[k].std(ddof=1) if len(per_seed[k]) > 1 else 0:.4f}"
        for k in cols) + " |")

    o += ["\n## False alarms at the shipped threshold\n",
          "5-fold calibration on train normals, tolerance bound at a 1% target. The rate is "
          "measured on the test normals, which are few, so the Wilson 95% interval is wide. "
          "Seed 0 is shown with its interval; the last column is the range over all seeds.\n",
          "| category | test normals | false alarms (seed 0) | FAR | Wilson 95% | "
          "FAR range over seeds |", "|---|---|---|---|---|---|"]
    tot_fa = tot_n = 0
    for r in runs:
        s0 = r["seeds"][0]
        fars = [s["far"] for s in r["seeds"]]
        tot_fa += s0["false_alarms"]
        tot_n += s0["n_normal"]
        lo, hi = s0["far_wilson95"]
        o.append(f"| {r['category']} | {s0['n_normal']} | {s0['false_alarms']} | "
                 f"{s0['far']:.1%} | [{lo:.1%}, {hi:.1%}] | {min(fars):.1%} to {max(fars):.1%} |")
    lo, hi = wilson(tot_fa, tot_n)
    o.append(f"| all | {tot_n} | {tot_fa} | {tot_fa / tot_n:.1%} | [{lo:.1%}, {hi:.1%}] | |")
    return "\n".join(o) + "\n"


def demo() -> None:
    """Wilson interval against R: prop.test(k, n, correct = FALSE)$conf.int."""
    lo, hi = wilson(0, 20)
    assert lo == 0.0 and abs(hi - 0.16113) < 1e-5, hi
    lo, hi = wilson(7, 28)
    assert abs(lo - 0.12676) < 1e-5 and abs(hi - 0.43356) < 1e-5, (lo, hi)
    print("self-check ok")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("categories", nargs="*", default=CATEGORIES)
    p.add_argument("--seeds", type=int, default=5)
    p.add_argument("--table-only", action="store_true")
    p.add_argument("--self-check", action="store_true")
    a = p.parse_args()
    if a.self_check:
        demo()
    else:
        if not a.table_only:
            for c in a.categories:
                run(c, list(range(a.seeds)))
        (ROOT / "reports" / "seeds.md").write_text(table())
