"""Compare this PatchCore with anomalib's, on the same images and the same metric code.

anomalib is not a project dependency. Install it in its own environment and
run this file with that interpreter; it imports the repo's dataset and metric
modules by path:

    uv venv /tmp/anomalib-venv
    VIRTUAL_ENV=/tmp/anomalib-venv uv pip install anomalib==2.7.0 scikit-learn matplotlib
    /tmp/anomalib-venv/bin/python src/edd/vs_anomalib.py bottle screw --seeds 5

The table against this repo's own runs (reports/seeds/, from seeds.py) needs
no anomalib:

    uv run python src/edd/vs_anomalib.py --table-only

What is shared: the image files, the preprocessing (Resize(256) + CenterCrop(224),
ImageNet normalisation, from dataset.py), the masks, and every metric
(baseline.evaluate for image AUROC, explain.localisation_metrics for pixel
AUROC and AUPRO).

What is anomalib's own: its PatchcoreModel, which means its timm
WideResNet50-2 feature extractor, its k-center greedy coreset, its image score
(the paper's reweighting over 9 neighbours, which this repo leaves out) and its
anomaly map (Gaussian blur, sigma 4). Its Lightning engine, pre-processor and
evaluator are not used, so nothing about the inputs or the scoring differs
except the model.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

import numpy as np
import torch
from torch.utils.data import DataLoader

sys.path.insert(0, str(Path(__file__).resolve().parent))

from baseline import evaluate  # noqa: E402
from dataset import MVTecCategory  # noqa: E402
from explain import localisation_metrics  # noqa: E402
from patchcore import device, device_name  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]


def run(category: str, ratio: float, seed: int, dev: torch.device) -> dict:
    from anomalib.models.image.patchcore.torch_model import PatchcoreModel

    torch.manual_seed(seed)
    np.random.seed(seed)
    t0 = time.time()
    model = PatchcoreModel(layers=["layer2", "layer3"], backbone="wide_resnet50_2").to(dev)

    model.train(True)             # train mode collects embeddings
    for img, *_ in DataLoader(MVTecCategory(category, "train", 224, True), batch_size=8):
        model(img.to(dev))
    model.subsample_embedding(ratio)

    model.train(False)            # inference mode returns scores and maps
    scores, maps, masks, labels = [], [], [], []
    with torch.no_grad():
        for img, label, mask, _ in DataLoader(MVTecCategory(category, "test", 224, True),
                                              batch_size=8):
            out = model(img.to(dev))
            scores.append(out.pred_score.cpu().reshape(-1))
            maps.append(out.anomaly_map.cpu()[:, 0])
            masks.append(mask[:, 0])
            labels.append(label)
    scores = torch.cat(scores).numpy()
    labels = torch.cat(labels).numpy()
    loc = localisation_metrics(torch.cat(maps).numpy(), torch.cat(masks).numpy(),
                               np.random.default_rng(seed))["model"]
    return {"category": category, "coreset_ratio": ratio, "seed": seed,
            "image_auroc": evaluate(labels, scores)["image_auroc"],
            "pixel_auroc": loc["pixel_auroc"], "aupro": loc["aupro"],
            "bank_size": int(model.memory_bank.shape[0]),
            "seconds": round(time.time() - t0, 1)}


def table(ratio: float = 0.01) -> str:
    """reports/anomalib.md: this repo (reports/seeds/) against anomalib, seed for seed."""
    cols = ("image_auroc", "pixel_auroc", "aupro")
    o = ["# Against anomalib PatchCore\n",
         "Generated by `src/edd/vs_anomalib.py --table-only`. Same images, preprocessing, "
         f"masks, seeds and metric code; {ratio:.0%} coreset for both. Mean and sample "
         "standard deviation over seeds. `diff` is ours minus anomalib's mean.\n"]
    per_seed = {("ours", k): [] for k in cols} | {("anomalib", k): [] for k in cols}
    rows, devices = [], set()
    for f in sorted((ROOT / "reports" / "anomalib").glob(f"*_{ratio:g}.json")):
        theirs = json.loads(f.read_text())
        c = theirs["runs"][0]["category"]
        mine = ROOT / "reports" / "seeds" / f"{c}.json"
        if not mine.exists():
            continue
        ours = json.loads(mine.read_text())
        devices |= {theirs["device"], ours["device"]}
        a_seeds = [r["seed"] for r in theirs["runs"]]
        o_rows = {r["seed"]: r for r in ours["seeds"]}
        assert all(s in o_rows for s in a_seeds), f"{c}: seeds differ"
        cells = []
        for k in cols:
            v_o = np.array([o_rows[s][k] for s in a_seeds])
            v_a = np.array([r[k] for r in theirs["runs"]])
            per_seed["ours", k].append(v_o)
            per_seed["anomalib", k].append(v_a)
            cells.append(f"{v_o.mean():.4f} ± {v_o.std(ddof=1):.4f} | "
                         f"{v_a.mean():.4f} ± {v_a.std(ddof=1):.4f} | "
                         f"{v_o.mean() - v_a.mean():+.4f}")
        rows.append(f"| {c} | " + " | ".join(cells) + " |")
    means = []
    for k in cols:
        m_o = np.mean(per_seed["ours", k], axis=0)
        m_a = np.mean(per_seed["anomalib", k], axis=0)
        means.append(f"{m_o.mean():.4f} ± {m_o.std(ddof=1):.4f} | "
                     f"{m_a.mean():.4f} ± {m_a.std(ddof=1):.4f} | {m_o.mean() - m_a.mean():+.4f}")
    o.append(f"Device: {', '.join(sorted(devices))}. {len(rows)} categories, "
             f"{len(a_seeds)} seeds each.\n")
    o += ["| category | image AUROC, ours | anomalib | diff | pixel AUROC, ours | anomalib | "
          "diff | AUPRO, ours | anomalib | diff |", "|---" * 10 + "|"]
    o += rows + ["| mean | " + " | ".join(means) + " |"]
    return "\n".join(o) + "\n"


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("categories", nargs="*")
    p.add_argument("--ratio", type=float, default=0.01)
    p.add_argument("--seeds", type=int, default=1)
    p.add_argument("--table-only", action="store_true")
    a = p.parse_args()
    if a.table_only:
        (ROOT / "reports" / "anomalib.md").write_text(table(a.ratio))
        raise SystemExit
    import anomalib

    dev = device()
    out_dir = ROOT / "reports" / "anomalib"
    out_dir.mkdir(parents=True, exist_ok=True)
    for c in a.categories:
        rows = []
        for s in range(a.seeds):
            r = run(c, a.ratio, s, dev)
            rows.append(r)
            print(f"{c:11} seed {s} | img {r['image_auroc']:.4f} | px {r['pixel_auroc']:.4f} "
                  f"| aupro {r['aupro']:.4f} | bank {r['bank_size']} | {r['seconds']:.0f}s",
                  flush=True)
        (out_dir / f"{c}_{a.ratio:g}.json").write_text(json.dumps(
            {"anomalib_version": anomalib.__version__, "torch_version": torch.__version__,
             "device": device_name(dev), "runs": rows}, indent=1))
